//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Console.GeneratorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeneratorService.GeneratorSoap")]
    public interface GeneratorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneratorLiczb", ReplyAction="*")]
        int GeneratorLiczb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneratorLiczb", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GeneratorLiczbAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GeneratorSoapChannel : Client_Console.GeneratorService.GeneratorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneratorSoapClient : System.ServiceModel.ClientBase<Client_Console.GeneratorService.GeneratorSoap>, Client_Console.GeneratorService.GeneratorSoap {
        
        public GeneratorSoapClient() {
        }
        
        public GeneratorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneratorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneratorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneratorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GeneratorLiczb() {
            return base.Channel.GeneratorLiczb();
        }
        
        public System.Threading.Tasks.Task<int> GeneratorLiczbAsync() {
            return base.Channel.GeneratorLiczbAsync();
        }
    }
}
